### PR TITLE
Solved error during decode

### PR DESCRIPTION
**Pull request by Shujian2015**
Didn't find the reason but this change made it works

### CODE REVIEW

**Comment by seungwonpark** [comment]
Thank you for your contribution!
Could you briefly describe the error you are trying to solve with this commit? And what's your tensorflow's version?

**Comment by Shujian2015** [comment]
Sure. When I used your code to decode, there is an error about .value in this line: https://github.com/seungwonpark/pointer-generator/blob/master/model.py#L48. After I deleted them from L48-50. It works.... I didn't find the exact reason.

**Comment by seungwonpark** [comment]
Obviously, line 52 has an error that should be fixed: I forgot to add `.value` here.
But I can't figure out why this commit works, and previous version don't.

Could you show the error message from the previous version? And are you using tensorflow version `>=1.5.0`?

**Comment by Shujian2015** [comment]
Sure, but probably sometime next week. I am using TF 1.5.

**Comment by Shujian2015** [comment]
Here is the error during decoding:

> File "<some path>/pointer-generator-master/model.py", line 48, in _add_placeholders
>     self._dec_batch = tf.placeholder(tf.int32, [hps.batch_size.value, hps.max_dec_steps.value], name='dec_batch')
> AttributeError: 'int' object has no attribute 'value'

**Comment by seungwonpark** [comment]
Great. Seems like `hps.max_dex_steps` is already `int`, so we should not append `.value` to it.
I will merge it. Thank you very much!

**Comment by Shujian2015** [comment]
The weird thing is if I delete it, there will be an error during training :( I am not a TF expert. It would be great if you could dig into this issue. Anyway, many thanks for modifying this project to work with TF 1.5. It helps me a lot!

**Comment by Shujian2015** [comment]
It is highly possible because of this line: https://github.com/seungwonpark/pointer-generator/blob/master/run_summarization.py#L316 It is already an int (1).
